### ISSUE TITLE
pXY loss not dropping

### ISSUE THREAD

**Issue by shervn** [dingdingcai/SC6D-pose#4]
Hi! Many thanks for the cool repo and paper. I'm training the network on a custom dataset, but pXY is not dropping, and therefore the results are not satisfactory. While you were training your networks, did you face such an issue? Do you have any recommendations to improve this? Many thanks in advance!

**Comment by dingdingcai** [comment]
Thanks for your interest in our work! I didn't encounter any issue regarding the object center offset regression (delta_Pxy). Regressing delta_Pxy is a relatively easy sub-task compared to other components because it is just the object's origin projection offset percent (usually within [-0.5, 0.5]) from the cropped image center. 

Please make sure that the ground-truth labels for delta_Pxy are correctly calculated, for example, by visually checking the ground-truth.

**Comment by shervn** [comment]
Thanks!!
